twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        inventory_service: '@App\Service\InventoryService'
        recipe_service: '@App\Service\RecipeService'
